name: chat
description: MCFEF chat app.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
#  google_fonts: 2.1.0
  jiffy: 4.1.0
  equatable: 2.0.3
  flutter_bloc: 8.0.1
  bloc_concurrency: 0.2.0
  flutter_slidable: 1.2.0
  focused_menu: 1.0.5
  http: 0.13.5
  flutter_secure_storage: 9.0.0
  intl: 0.17.0
  provider: 6.0.2
  image_picker: 0.8.5+3
  path_provider: 2.0.13
  swipe_to: 1.0.2
  just_audio: 0.9.24
  flutter_linkify: 5.0.2
  url_launcher: 6.1.5
  cupertino_icons: 1.0.2
  record: 4.0.2
  web_socket_channel: 2.2.0
  dart_pusher_channels: 1.1.0
  flutter_sound: 9.2.13
  flutter_sound_platform_interface: 9.2.13
  easy_pdf_viewer: 1.0.4
  pdf: 3.8.3
  gallery_saver: 2.3.2
  image_picker_for_web: 2.1.10
  package_info_plus: 4.1.0
  universal_html: 2.0.8
  flutter_ringtone_player: 3.2.0
  file_picker: 5.5.0
  permission_handler: 10.2.0
  audioplayers: 5.2.0
  path_provider_foundation: ^2.1.2
  flutter_callkit_incoming: ^2.0.0+2
  flutter_image_compress: ^2.0.0
  firebase_crashlytics: ^3.4.5

  firebase_analytics: ^10.7.1 # Do we need it?

  flutter:
    sdk: flutter
  firebase_core: ^2.23.0

dev_dependencies:
  flutter_lints: ^1.0.0
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/images/
   - assets/sounds/

