// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDez4PxlgwYs61lAd3tvbmXgP3iRQMV-DA',
    appId: '1:671710503893:web:ddfbcbedfb3a4e2197535c',
    messagingSenderId: '671710503893',
    projectId: 'cashalot-fl',
    authDomain: 'cashalot-fl.firebaseapp.com',
    storageBucket: 'cashalot-fl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBesVvyI339DO5DenOxQaZC80W4kDu5OyA',
    appId: '1:671710503893:android:9a8e318c84b6a0ad97535c',
    messagingSenderId: '671710503893',
    projectId: 'cashalot-fl',
    storageBucket: 'cashalot-fl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAWI2Xl2pdw3IZM05JW0sLbLshPoJmBrg',
    appId: '1:671710503893:ios:aa197b089d35d70097535c',
    messagingSenderId: '671710503893',
    projectId: 'cashalot-fl',
    storageBucket: 'cashalot-fl.appspot.com',
    iosBundleId: 'com.application.mcfef.chat',
  );
}
